export const APP_SETTINGS = {
  company: {
    name: 'DestineVents Collective OPC',
    shortName: 'DestineVents',
    founder: 'Jennifer Castro, Founder',
    address: 'Baguio City, Philippines',
    email: 'destinevents.biz@gmail.com',
    brand: 'DestineVents',
    brands: ['DestineVents', 'DDC', 'AYA'],
  },
  intern: {
    companyName: 'Disenyo Digitals Collective OPC',
    maxDailyHours: 8,
    minHoursEntry: 0.5,
    maxHoursEntry: 10,
    hourStep: 0.5,
  },
  finance: {
    deductionRate: 0.15,
    birYear: 2026,
    ewtRates: ['0%', '2%', '5%', '10%', '15%'],
    clientTypes: ['Government', 'Corporate', 'Education', 'NGO', 'Community', 'Startup'],
    clientStatuses: ['Lead', 'Active', 'NDA Signed', 'Completed'],
    proposalStatuses: ['Draft', 'Sent', 'Won', 'Lost', 'Expired'],
    invoiceStatuses: ['Unpaid', 'Paid', 'Overdue'],
    billStatuses: ['Unpaid', 'Paid'],
    billCategories: [
      'Venue',
      'Catering',
      'Equipment',
      'Services',
      'Transport',
      'Supplies',
      'Other',
    ],
    payrollStatuses: ['Draft', 'Pending', 'Paid'],
  },
  ai: {
    apiUrl: 'https://api.anthropic.com/v1/messages',
    apiVersion: '2023-06-01',
    model: 'claude-haiku-4-5-20251001',
    storageKey: 'anthropic_api_key',
  },
  storage: {
    auditLogKey: 'audit_logged',
    sidebarKey: 'sidebar_collapsed',
  },
  events: {
    statuses: ['Upcoming', 'Active', 'Completed', 'Cancelled'],
    types: [
      'Corporate', 'Government', 'CSR',
      'Community', 'Pop-up', 'Workshop',
      'Training', 'Digital Workshop', 'Expo',
    ],
  },
  app: {
    url: 'https://destine-vents-command-center.vercel.app',
  },
  payments: {
    currency: 'PHP',
    successPath: '/payment-success.html',
    cancelPath: '/register.html',
    methods: ['gcash', 'card', 'paymaya', 'grab_pay'],
  },
  banking: {
    tin: '',
    bpiAccountName: 'Destine Vents Events Management Services',
    bpiBranch: 'BPI Baguio Legarda',
    bpiAccountNumber: '8129-1500-42',
    bpiQrImageUrl: '/assets/images/bpi-qr.png',
  },
};
